"""rename username to email

Revision ID: 1dd5ee8ce4d0
Revises: 184bd42ea4a2
Create Date: 2026-02-23 21:55:56.403389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd5ee8ce4d0'
down_revision: Union[str, Sequence[str], None] = '184bd42ea4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    # ### end Alembic commands ###
